### ISSUE TITLE
ResearchGate changed their icon

### ISSUE THREAD

**Issue by ChemPaul** [jpswalsh/academicons#10]
Since ResearchGate changed their icon, can we get an updated version?

**Comment by jpswalsh** [comment]
I had noticed. I kind of hoped it was just a placeholder, because they've managed to make it even worse than the previous one! I'll add the new version soon.

**Comment by ChemPaul** [comment]
Yeah...not the nicest looking thing ever...but thanks for being willing to add it to the set!

**Comment by jpswalsh** [comment]
Added the new version to v1.5. The old icons can still be accessed using `researchgate-old` and `researchgate-old-square`, if needed.
