### ISSUE TITLE
protocols.io

### ISSUE THREAD

**Issue by fernan** [jpswalsh/academicons#100]
Add an icon for protocols.io to the list of academic icons. 
https://www.protocols.io

![image](https://user-images.githubusercontent.com/175475/57319184-66b39900-70d2-11e9-9d26-c564072f4abc.png)

[favicon.ico.zip](https://github.com/jpswalsh/academicons/files/3153789/favicon.ico.zip)

**Comment by IdoBar** [comment]
+1 here
