### ISSUE TITLE
Open Access

### ISSUE THREAD

**Issue by cht** [jpswalsh/academicons#11]
Hi James,

Thanks for this effort - font based icons within academia are really useful in som many contexts.  Love to see this grow.

Adding the icon for Open Access [1] would make the set even more useful.  Hope this can be accomplished.

Cheers,
Christian

[1] https://commons.wikimedia.org/wiki/File:Open_Access_logo_PLoS_white.svg

**Comment by jpswalsh** [comment]
Thanks for the feedback! An icon for Open Access has been added to v1.6.0.
