### ISSUE TITLE
Icon Request: LaTeX

### ISSUE THREAD

**Issue by gregorypenn** [jpswalsh/academicons#111]
Could you please add an icon for the LaTeX logo? Specifically, I'd like the name LaTeX traditionally typeset as in the image below (as \LaTeX). 

![200px-LaTeX_logo](https://user-images.githubusercontent.com/2105889/64950930-cd438300-d839-11e9-9dd4-56173e40e66a.png)

Ideally, we'd also have an icon for the bird from the official logo below. I understand that the LaTeX name might be too wide for a good icon, in which case the bird would be a good alternative. It's less well recognized, but fits an icon's aspect ratio well

![latex-project-logo](https://user-images.githubusercontent.com/2105889/64950763-658d3800-d839-11e9-900d-6de22ce4cdf9.png)

**Comment by astrochun** [comment]
👍 

I was looking for one as well.  Thank you.

**Comment by diogo-fernan** [comment]
Nice one!

**Comment by nfrerebeau** [comment]
Academicons contains icons for websites and organisations related to academia. Software and markup/programming languages are out of scope.
