### ISSUE TITLE
Styling clash with stacked FontAwesome

### ISSUE THREAD

**Issue by nurfatimaj** [jpswalsh/academicons#112]
Hi!
I wanted to use the academicons on my website, where I already have a bunch of icons from FontAwesome. I usually stack the FontAwesome icons on top of a circle icon and invert them:
```
<span class="fa-stack fa-lg">
      <i class="fa fa-circle fa-stack-2x"></i>
      <i class="fas fa-location-arrow fa-stack-1x fa-inverse"></i>
</span>
```
to get this at the end:
![image](https://user-images.githubusercontent.com/24235395/65363482-76a8c100-dc0c-11e9-8ff6-34d3ea603f75.png)

But after I included academicons into my header using 
```
<link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">
```
the previously stacked icons are misaligned with each other. Instead of the main fontawesome icon appearing at the center of the circle, it is now placed to the top of the circle:
![image](https://user-images.githubusercontent.com/24235395/65363459-5973f280-dc0c-11e9-8d21-e9899b0d218f.png)

All I know right now is that if I remove the link to academicons from the header, I again get the normal alignment. Could you help solve this please?

Thank you!

**Comment by jklaise** [comment]
I have the same issue when using FontAwesome+Academicons on a [Beautiful Hugo](https://github.com/halogenica/beautifulhugo) themed website.
