### ISSUE TITLE
Icon shape round

### ISSUE THREAD

**Issue by cgirerd** [jpswalsh/academicons#113]
Hello,
Thank you very much for providing the academicons package. I know it is possible to have square icons. I am wondering if it would be possible to have round icons as well. I am happy to contribute to this work if that can help make it possible.
Best,
Cedric

**Comment by nfrerebeau** [comment]
You can style the icons using Font Awesome CSS controls. See stacked icons at https://jpswalsh.github.io/academicons/usage.
