### ISSUE TITLE
zip file as part of the source

### ISSUE THREAD

**Issue by nschloe** [jpswalsh/academicons#12]
I noticed that commit 0bc9db8390e114b3de44301e8248d2fd5ef9c537 moved zipped file of the version controlled content into version control. This is generally not advised because:

   1. The contents of the file are already contained in the tree.
   2. Binary files are poorly handled by vcs.

Creating a zip file is rather done as a post processing step. For example, you will notice that GitHub provides nice downloads of the release tags https://github.com/jpswalsh/academicons/releases.

Moreover, I see in the commit history https://github.com/jpswalsh/academicons/commits/master lots of entries like "removed v1.*". It is however not necessary to explicitly remove a version. The general scheme would be that you develop your code in, e.g., the folder `fonts`, and tag a commit with `1.6` whenever you think it's ready. No need to keep separate folders for separate releases or anything.

**Comment by jpswalsh** [comment]
Thanks. I've followed your advice.
