### ISSUE TITLE
Icon Request: EnergyFlow

### ISSUE THREAD

**Issue by pkomiske** [jpswalsh/academicons#126]
This is an icon request for the scientific computing package [EnergyFlow](https://energyflow.network). 

File: [logo.pdf](https://github.com/jpswalsh/academicons/files/4466864/logo.pdf)

The logo is currently colored red but can easily be made monochrome as it is all the same color.

**Comment by nfrerebeau** [comment]
Academicons contains icons for websites and organisations related to academia. Software and markup/programming languages are out of scope.
