### ISSUE TITLE
provide bower package

### ISSUE THREAD

**Issue by nschloe** [jpswalsh/academicons#13]
To use academicons from a JS project, it's nowadays customary to include the project in package repository, the most popular being bower and npm. Given that this is front-end code, it'd make much sense to provide a `bower.json` with academicons. All packages I'm aware of to that, specifically [fontawesome](https://github.com/FortAwesome/Font-Awesome/blob/master/bower.json).

**Comment by jpswalsh** [comment]
I've now added a bower package.

**Comment by nschloe** [comment]
```
bower invalid-meta  academicons is missing "ignore" entry in bower.json
```

**Comment by jpswalsh** [comment]
Fixed. Thanks.
