### ISSUE TITLE
Academicons 2.0 ?

### ISSUE THREAD

**Issue by nfrerebeau** [jpswalsh/academicons#136]
@jpswalsh I recently [forked](https://github.com/nfrerebeau/academicons) Academicons and add 17 new icons (with square version): 

- AfricArxiv (#123)
- Ciência Vitae (#122)
- The Conversation (#56)
- CrossRef (#64)
- DataCite (#129)
- Elsevier (#80)
- HAL (#99)
- Isidore and Nakala (#93)
- JSTOR (#104)
- Open Science Badges: open data, open material and preregistered (#77, #103)
- OpenEdition
- protocols.io (#100)
- Sci-Hub (#81)
- Closed Access (#79)

I also fixed Semantic Scholar icon (#133).

All icons were redesigned on a 16px grid to follow FontAwesome 5 (svg files included; #116). Font files were generated with [FontForge](https://fontforge.org) and [ttf2eot](https://www.npmjs.com/package/ttf2eot) for better baseline alignment.

Query strings were removed in the CSS (#78).

Are you interested by a PR ?

**Comment by nfrerebeau** [comment]
On the downside, I changed the unicode values of the glyphs (using the Private Use Area) when creating the font in FontForge. As I know nothing about unicode encoding I'm not sure of what I've done.

**Comment by mra42** [comment]
Thank you for your work. Any chance of also fixing the dblp icon (#51) with the already provided SVG file?

[icon_dblp_bw.svg.zip](https://github.com/jpswalsh/academicons/files/1914757/icon_dblp_bw.svg.zip)

**Comment by jpswalsh** [comment]
This sounds like a great contribution. Yes, please do go ahead and submit a pull request. Do you have a page set up where the icons can be viewed (both new and old/improved)?

For "v2.0" I have actually started migrating to a workflow that uses [FontCustom](https://github.com/FontCustom/fontcustom). The benefit of this is that contributors would only have to submit an SVG, which would be pulled into an `svg/` folder and incorporated into a new version of the font with a single compile step. I made some progress, but haven't had the time to put it all together. Let me know if you would like to take over this, or if you have other ideas.

As for the unicode values, there was nothing special about the order I had. This is something I've worried about before, but for most users it doesn't seem to affect things. Still, it would be good to stick to a consistent set of values going forward.

**Comment by nfrerebeau** [comment]
@jpswalsh thanks! I add a test page in the test/ directory, but it only shows the new/modified icons.

The FontForge file is in the source/ directory. FontCustom seems to be a good option. I'll try to take a closer look and see if I can help.

I set the unicode values back to the original values.

PR is on its way!

(@mra42: I fixed it)
