### ISSUE TITLE
Since link update, Academicons do not work.

### ISSUE THREAD

**Issue by flavioazevedo** [jpswalsh/academicons#142]
Dear JP Walsh, 

Apologies in advance for this is my first ticket. I have a website built in Rmarkdown which was online for a month. I updated a typo (and nothing more) a few hours ago and the academicons disappeared. You can see it here (https://icsmp-covid19.netlify.app), at the footer, that now it only displays empty squares instead of Academicons. I am 100% sure nothing else change as I have checked the GitHub App log. Before, I used it like so.

/* Academicons */
<link rel="stylesheet" href="https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css">

I saw in your Github you updated the link, so I substituted the above link for:
https://cdn.jsdelivr.net/**gh**/jpswalsh/academicons/css/academicons.min.css 

Thank you very much!

Best,
F/
![image](https://user-images.githubusercontent.com/18330492/90073113-ef1ee180-dcf8-11ea-96a3-e8149cc5820a.png)
![image](https://user-images.githubusercontent.com/18330492/90073145-ffcf5780-dcf8-11ea-90c8-23f69df93f1b.png)

**Comment by nfrerebeau** [comment]
The rawgit CDN is closing down, you have to update the link to https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css.

**Comment by jhollway** [comment]
@nfrerebeau, is there a subresource integrity hash (SHA256) for use in e.g. Hugo websites?

**Comment by nfrerebeau** [comment]
cdnjs provides a SRI hash you can use with Hugo: https://cdnjs.com/libraries/academicons
