### ISSUE TITLE
Icon request: Fossil-scm.org

### ISSUE THREAD

**Issue by ezaron** [jpswalsh/academicons#143]
Thanks for putting together this great package.
I understand the existing icon is not perfectly sized for this font, but if it is close enough that you can consider adding it, I would be most appreciative:
https://fossil-scm.org/home/file?name=www/fossil_logo_small3.gif

**Comment by nfrerebeau** [comment]
Academicons contains icons for websites and organisations related to academia. Software and markup/programming languages are out of scope.
