### ISSUE TITLE
Icon request: GnuPG

### ISSUE THREAD

**Issue by ezaron** [jpswalsh/academicons#144]
Another icon request. This one has svg:

https://dev.gnupg.org/source/gnupg/browse/master/artwork/icons/lock-wing.svg

And here is the sqaure favicon version they already have, for reference:

https://dev.gnupg.org/source/gnupg/browse/master/artwork/gnupg-favicon-2.ico

**Comment by nfrerebeau** [comment]
Academicons contains icons for websites and organisations related to academia. Software and markup/programming languages are out of scope.
