### ISSUE TITLE
Icons missing in .eot version

### ISSUE THREAD

**Issue by ntapiam** [jpswalsh/academicons#145]
Hi!
I tried to use your icons on my website, but the "Scopus" icon was not displaying on Firefox.
The same is true for me in [your gallery](http://jpswalsh.github.io/academicons), along with other icons (hypothesis, obp, ror, and zenodo).

<img width="737" alt="image" src="https://user-images.githubusercontent.com/1558791/100219726-a17c5c80-2f16-11eb-9e18-af2d639c70dd.png">

Getting rid of the .eot font fixed the issue, see diff below.

```diff
--- academicons.css	2020-11-25 11:59:08.000000000 +0100
+++ academicons.css.new	2020-11-25 11:59:17.000000000 +0100
@@ -9,11 +9,10 @@
     font-style: normal;
     font-weight: 400;
     font-display: block;
-    src: url('../fonts/academicons.eot');
-    src: url('../fonts/academicons.eot') format('embedded-opentype'),
-         url('../fonts/academicons.ttf') format('truetype'),
-         url('../fonts/academicons.woff') format('woff'),
-         url('../fonts/academicons.svg') format('svg');
+    src: url('../fonts/academicons.woff');
+    src: url('../fonts/academicons.ttf') format('truetype'),
+        url('../fonts/academicons.woff') format('woff'),
+        url('../fonts/academicons.svg') format('svg');
 }
 .ai {
   font-family: 'Academicons';
```

As I have no way of opening the .eot font, I cannot check its contents, but the glyphs seem to be there in all the other versions.

Thanks!

**Comment by nfrerebeau** [comment]
The missing icons in the gallery are those that have been added but not yet released (coming soon). The .eot font is not up to date and must be generated from the .ttf file.

**Comment by nfrerebeau** [comment]
Version 1.9.1 has just been released. All the icons in the gallery should be available.

**Comment by ntapiam** [comment]
Thanks!
