### ISSUE TITLE
An DOI Icon

### ISSUE THREAD

**Issue by kellertuer** [jpswalsh/academicons#15]
hi there,
great to have additional icons for science related stuff - however, I would like to have an DOI icon, would it be possible to get something like that? Would be awesome.

**Comment by kyleniemeyer** [comment]
+1 a DOI icon.

It looks like there is an available svg icon that might be a good starting place: https://upload.wikimedia.org/wikipedia/commons/1/11/DOI_logo.svg

**Comment by jpswalsh** [comment]
I've added the DOI icon to v1.7.0, based on the provided SVG (thanks!).
