### ISSUE TITLE
Update to the Crossref icon?

### ISSUE THREAD

**Issue by ynnig** [jpswalsh/academicons#155]
Hi - could I request an update to the Crossref icon to fit our style guide? There is a single colour (full) logo attached that perhaps you could take the icon from, or I can ask a designer if needed? Many thanks for this work - it's much appreciated! 
[crossref-singlecolour-logo.zip](https://github.com/jpswalsh/academicons/files/6147579/crossref-singlecolour-logo.zip)

**Comment by nfrerebeau** [comment]
Thanks for providing the new icon, the update is done (sorry for the delay).

**Comment by ynnig** [comment]
Hi @nfrerebeau, I think I must have attached the wrong one. I only just checked it now! Can you try with this one? Basically the lines between the five shapes making up the icon should be visible.
![Crossref_Logo_Stacked_SingleColor_Logo](https://user-images.githubusercontent.com/6958740/141523583-195d8fa5-e0ed-415e-9464-358eef69c825.png)
