### ISSUE TITLE
Icon request: INSPIRE-HEP

### ISSUE THREAD

**Issue by nathanmusoke** [jpswalsh/academicons#16]
[INSPIRE-HEP](http://inspirehep.net/) is the leading literature database for high energy physics. Could you add an icon for it? Their favicon is at http://inspirehep.net/favicon.ico.
If you'd prefer, I could try to make one and submit a pull request - just tell me what needs to be done.

Thanks for taking the time to provide what Font Awesome hasn't.

**Comment by jpswalsh** [comment]
That icon file seems to be the only version of the logo, so I made it from scratch and added it to v1.7.0. Hope it's useful!

**Comment by nathanmusoke** [comment]
That looks great -- thank you very much!

I'll have it up at nathan.musoke.ca soon.

**Comment by nathanmusoke** [comment]
That looks great -- thank you very much!

I'll have it up on my [website](http://nathan.musoke.ca) soon.

**Comment by Fcornetg** [comment]
Hello, I can't find the icon. It also seems that it have changed since the Nathan request. The squared version lookslike: https://pbs.twimg.com/profile_images/1234490198618185730/YDsnDGEQ_400x400.jpg
Would you be so kind of adding it?
Thanks!

**Comment by Fcornetg** [comment]
Here is the .eps, just ins case it helps.
[HEP-Mod.zip](https://github.com/jpswalsh/academicons/files/5857116/HEP-Mod.zip)
