### ISSUE TITLE
Bug that makes it impossible to display the Springer icon?

### ISSUE THREAD

**Issue by IlseO76** [jpswalsh/academicons#161]
Hi James, thanks so much for the academicons set! It is really great to have this available. 

Question: I cannot get the Springer icon to display, even though I've checked and rechecked that I'm using the same code that I use for displaying other academicons, and I've used the correct icon name (springer). 

Might there be something wrong in how Springer is included in the repository?

**Comment by nfrerebeau** [comment]
Works fine here : <https://jpswalsh.github.io/academicons/> 

Could you provide a link to your code/website?
