### ISSUE TITLE
Scopus and iNaturalist icons do not appear

### ISSUE THREAD

**Issue by jimarcor** [jpswalsh/academicons#162]
I have succeeded in including different icons from Academicons, but somehow iNaturalist and Scopus icons do not show up using the following command (as used likewise for the other icons):

        <li><a href="{{ author.inaturalist }}"><i class="ai ai-inaturalist ai-fw"></i> iNaturalist</a></li>

I think it's a bug in these two because I have also tried the square version, unsuccessfully.

Thank you

**Comment by nfrerebeau** [comment]
I can't reproduce your issue on my side. Could you provide a link to your website?

**Comment by jimarcor** [comment]
This is the website: https://jimarcor.github.io/
The icons should be displayed in the left column, as the others do.

Thnks

**Comment by nfrerebeau** [comment]
Your are using Academicons 1.8.0. If you want to use these icons, you must use v1.9.1. See the instructions: <https://jpswalsh.github.io/academicons/#how-do-i-use-it>

**Comment by jimarcor** [comment]
Thank you, this has fixed the problem!

All the best
