### ISSUE TITLE
Icon Request: Creative Commons

### ISSUE THREAD

**Issue by ja573** [jpswalsh/academicons#163]
SVG Creative commons icons:

- [cc](https://cloud.openbookpublishers.com/s/J7pjZ3RXy77jkDZ)
- [cc-by](https://cloud.openbookpublishers.com/s/n7x5BeSNSzQ94BA)
- [cc-nc](https://cloud.openbookpublishers.com/s/exxZ7f3rfTjMtnQ)
- [cc-nd](https://cloud.openbookpublishers.com/s/wBf8rZJMQgNxCR2)
- [cc-sa](https://cloud.openbookpublishers.com/s/3wBRyPAEEqGjZQK)
- [cc-zero](https://cloud.openbookpublishers.com/s/3t88NKY7X9dDtDb)

**Comment by machuangtao** [comment]
Icon Request: Library of Hungarian Scientific Works
![mtmt](https://user-images.githubusercontent.com/47854227/132921774-24ee9cc2-59c9-4b00-8e93-533b05f2a498.png)

**Comment by nfrerebeau** [comment]
Creative Commons icons are available in Font Awesome: <https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=creative-commons>

**Comment by ja573** [comment]
That was precisely the reason why I thought it'd be good to include them. I'm working on a project where I'm relying on academicons for all icons except for the Creative Commons' which I'm getting from font awesome. To me it'd be great if I could have one dependency instead of two, but fair enough if that's not academicons' point
