### ISSUE TITLE
Icon Request: Library of Hungarian Scientific Works

### ISSUE THREAD

**Issue by machuangtao** [jpswalsh/academicons#165]
Icon Request: Library of Hungarian Scientific Works
![mtmt](https://user-images.githubusercontent.com/47854227/132921913-9fa22bce-3d9a-472b-b0e9-10fac2b21149.png)

**Comment by nfrerebeau** [comment]
Duplicate of #97. Could you provide an svg version?

**Comment by machuangtao** [comment]
> Duplicate of #97. Could you provide an svg version?

Unfortunately, I couldn't find an official svg version of this icon. I found this one, I hope it works.
[mtmt2.zip](https://github.com/jpswalsh/academicons/files/7147590/mtmt2.zip)
