### ISSUE TITLE
Update INSPIRE-HEP icon to the current one

### ISSUE THREAD

**Issue by SageofthePHY6Paths** [jpswalsh/academicons#169]
Their current favicon is just i.
![image](https://user-images.githubusercontent.com/92218586/138641677-313dbae4-afbc-43fd-86c9-e84f16e983c0.png)
their current twitter logo is
![image](https://user-images.githubusercontent.com/92218586/140744914-eafd1283-3d07-4631-9073-1ce1ff820e0f.png)
either of them will be Ok for the icon.

The one on academicons is an old version.
![image](https://user-images.githubusercontent.com/92218586/138641782-968d9b13-61bf-4e6c-9289-a59b71f670c7.png)

**Comment by 0lelouch** [comment]
@nfrerebeau @jpswalsh

**Comment by SageofthePHY6Paths** [comment]
@nfrerebeau thanks

**Comment by SageofthePHY6Paths** [comment]
@nfrerebeau and @jpswalsh  I think the version of academicons is still on v1.9.2 (13 Mar 2022). It is not updated after your recent commit.

**Comment by nfrerebeau** [comment]
This is not an oversight, I hope to have time to fix a few more issues in the coming days before making a new release.

**Comment by SageofthePHY6Paths** [comment]
@nfrerebeau I see cool.
