### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by dpo** [jpswalsh/academicons#17]
Thanks for creating these icons! I'm trying to use them in a Jekyll site based on the [beautiful Jekyll](https://github.com/daattali/beautiful-jekyll) template. There's a row of (stacks of) Font-Awesome icons in the footer:
![screen shot 2016-04-04 at 17 37 59](https://cloud.githubusercontent.com/assets/38760/14264045/0431954e-fa8c-11e5-99f4-6bf4ddab0938.png)
But as soon as I include the Academicons css, their alignment gets out of whack:
![screen shot 2016-04-04 at 17 39 09](https://cloud.githubusercontent.com/assets/38760/14264073/2a0130b8-fa8c-11e5-94f0-a8c4a1084418.png)
If I try to add an Academicon to the row, I get this nonsense:
![screen shot 2016-04-04 at 17 39 36](https://cloud.githubusercontent.com/assets/38760/14264099/43e9ed58-fa8c-11e5-94a5-2dd7974798a8.png)
I apologize for my ignorance of all things css, but do you have any idea where the conflict might come from? The code for the footer is [here](https://github.com/daattali/beautiful-jekyll/blob/master/_includes/footer.html).

Thanks in advance!

**Comment by jpswalsh** [comment]
Hey,

Do you have a live version that I can inspect? The order in which you load
the CSS could be important, so a first quick try would be to change the
order the CSS is loaded. My second guess would be that you're trying to use
ai-stack, but this doesn't exist. The resizing classes were duplicated, but
not things like fa-stack, fa-rotate.

James

**Comment by dpo** [comment]
Thanks. I don't have a live version of the site yet, but it seems that the `<span>` elements in the footer template were causing trouble. I removed them along with the icons stacks to only use square icons and things align nicely now:

![screen shot 2016-04-13 at 12 50 09](https://cloud.githubusercontent.com/assets/38760/14501821/4c3885be-0176-11e6-8bab-0e34bde3e169.png)

Just in case someone else has the same issue.

**Comment by jpswalsh** [comment]
Hi Dominique,

Thanks for the update. I'm glad you figured it out. Looks good!

Regards,

James

**Comment by jonbra** [comment]
I had the exact same issue of alignment using a different jekyll template, [Minimal Mistakes](https://mmistakes.github.io/minimal-mistakes/). (And I also note a slight difference in space between the Academicons).

<img width="182" alt="screen shot 2017-01-27 at 19 26 56" src="https://cloud.githubusercontent.com/assets/16081233/22382598/9ec9a82e-e4c6-11e6-9c8f-070d08d132d9.png">

But I can't find any ´<span>´ elements causing trouble. Do you know more about what was causing the mis-alignmet?

**Comment by dpo** [comment]
I'm really not sure as my understanding of those things is very limited, but it might have to do with the css used to display the icons?! https://github.com/mmistakes/minimal-mistakes/blob/afb1ed4aad4a12e8c3102807016358edb0c46c03/_sass/_sidebar.scss#L127

**Comment by jonbra** [comment]
You're right. Changing from `ai-1x` to [`ai-fw`](https://github.com/jonbra/jonbra.github.io/blob/master/_includes/author-profile-custom-links.html#L6) fixed the horisontal alignment, and I added `margin-bottom: 8px;` to the `.css` to fix the vertical spacing between the elements.

**Comment by jpswalsh** [comment]
Jon, I just took a look at your site and I noticed that the two academic links are within the same `<li>` tag. Could that be the source of your vertical spacing problem? The `aria-hidden` property is also not defined for the new icons, but it is for the FontAwesome icons.

In any case, it looks good and I'm glad you got it working!

**Comment by jonbra** [comment]
Thanks! That fixed the vertical spacing so I could remove `margin-bottom:`

**Comment by fernandoandreotti** [comment]
Have a look at issue #3, re-ordering these declarations solved this for me. I was trying to add logos to the footer of a site based on the [beautiful-jekyll](https://deanattali.com/beautiful-jekyll/) template.

That is, on base.html
```
common-ext-css:
  - "/css/academicons.min.css"
  - "//maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css"  
```
