### ISSUE TITLE
Microsoft Academic is missing

### ISSUE THREAD

**Issue by 0lelouch** [jpswalsh/academicons#171]
Microsoft Academic is missing. Please add that.

**Comment by 0lelouch** [comment]
It is available here https://simpleicons.org/, maybe you can download the SVG and add it here.

**Comment by alsahahari** [comment]
I second this. Many thanks for your great effort and amazing job

**Comment by nfrerebeau** [comment]
The Microsoft Academic website and API were [retired on December 31, 2021](https://www.microsoft.com/en-us/research/project/academic/articles/microsoft-academic-to-expand-horizons-with-community-driven-approach/).
