### ISSUE TITLE
Error in .min.css v1.9.1

### ISSUE THREAD

**Issue by lenaMK** [jpswalsh/academicons#172]
Hello, 
Just downloaded the latest release (v1.9.1) and got an error in the academicon.min.css
Solved it following applying this correction  #151 that removes the typo from the .css
May I suggest to do the same with the .min.css?

**Comment by nfrerebeau** [comment]
The minified css is fixed in the development version, not in Academicons 1.9.1 which was released before #151.

You can download the development version [here](https://github.com/jpswalsh/academicons/archive/refs/heads/master.zip).
