### ISSUE TITLE
update arXiv logo

### ISSUE THREAD

**Issue by kc9jud** [jpswalsh/academicons#174]
arXiv has a new logo: https://arxiv.org/about/brand_use

I expect that the [small logomark](https://cornell.box.com/s/cleq2ex1wra4sfsj94tlqrw9z5oecg6b) is the most appropriate, but it may be best to ask them:
> Have questions? Need a different color? Please reach out to nextgen@arxiv.org with your request and include a link to your application.

In particular, they may have a monochrome version already available.

**Comment by chriscoey** [comment]
bump! this would be great.

**Comment by GilOliveira** [comment]
I've created a B&W SVG version of the arXiv... I would submit a PR but I'm not exactly sure all the files I need to change in order to update the icon. Anyways I've attached the SVG.

![arxiv-logomark-small_academicons](https://user-images.githubusercontent.com/1360438/177208058-3e6c74c2-2e82-4f0d-bbf1-9b86b6de623e.svg)

**Comment by MiguelBarq** [comment]
Bump, I have never seen the current icon and thought it was a bug when it rendered as such.

**Comment by nfrerebeau** [comment]
> Bump, I have never seen the current icon and thought it was a bug when it rendered as such.

This is not a bug, take a look at the favicon: https://arxiv.org/

**Comment by kc9jud** [comment]
> > Bump, I have never seen the current icon and thought it was a bug when it rendered as such.
> 
> This is not a bug, take a look at the favicon: https://arxiv.org/

That's debatable... I'm under the impression that arXiv is phasing out the old favicon. I'm not sure it's used anywhere except the favicon now. The new logo is used lots of places.

**Comment by kc9jud** [comment]
@nfrerebeau Have you already emailed arXiv directly? If not, I can send an email and see if someone from arXiv can come comment on this issue.

**Comment by nfrerebeau** [comment]
I just contacted the arXiv team to ask if there is a monochrome version of the new logo. If so, I could make the update.

**Comment by nfrerebeau** [comment]
@GilOliveira The thing is that this is an unofficial change to the logo. I think it is better to see if the arXiv team can provide us with a suitable logo.

**Comment by jweiskoff** [comment]
Hi! I'm arXiv's technical support manger. 

arXiv's official brand use guidelines are at: https://info.arxiv.org/brand/brand-guidelines.html and the existing icon for arXiv is indicated at the bottom of the page. The old "smiley bones" logo has been officially phased out. 

Please feel free to reach out to me at jake@arxiv.org to connect regarding getting an official black and white svg for your package from our UI/UX team.

**Comment by episanty** [comment]
This is great news! out of curiosity, how were the IP issues resolved?
