### ISSUE TITLE
Update to Crossref icon please

### ISSUE THREAD

**Issue by ynnig** [jpswalsh/academicons#176]
Hello again, I left a [comment](https://github.com/jpswalsh/academicons/issues/155#issuecomment-967379831) on issue 155 a couple of months ago but the issue had been closed so now opening a new one! Hoping for a fix for the Crossref icon. Many thanks.

**Comment by nfrerebeau** [comment]
The icon has been updated (see a0f7520), but the new version of Academicons has not yet been released. This should be done very soon.
