### ISSUE TITLE
Open Science Framework Icon?

### ISSUE THREAD

**Issue by oliviaguest** [jpswalsh/academicons#18]
Thanks so much for the amazing icons. I am using them on my [website](http://oliviaguest.com) - they are a total aesthetic lifesaver. 
Would it be possible to add an [OSF](https://osf.io/) icon? :smile:

**Comment by jpswalsh** [comment]
Glad you like them! I've added OSF in v1.7.0. It's a tricky logo to reduce to a single shape; it's the best I could do.
