### ISSUE TITLE
MTMT Icon Issue

### ISSUE THREAD

**Issue by diogo-fernan** [jpswalsh/academicons#180]
Hello guys! I am the author and maintainer of https://github.com/diogo-fernan/academicons and ran into an issue where the MTMT icon is not loading in LaTeX. This did not happen with a previous `academicons.ttf` font file and it now only happens with this icon despite that it seems to be visible at the very end in the Font Book on macOS:
![mtmt](https://user-images.githubusercontent.com/11231644/153927345-cc21df5e-7437-4063-9c6f-f51962c28ec1.png)

However, the MTMT icon does not come up with `ttfdump`:
```
  % ttfdump academicons.ttf | egrep -i mtmt                                                                                                                                                                                               
  % ttfdump academicons.ttf | egrep -i acm  # an example that works
		 Glyf   7  -> PSGlyf Name #   5, 'acm'
		 Glyf   8  -> PSGlyf Name #   6, 'acm-square'
		 Glyf   9  -> PSGlyf Name #   7, 'acmdl'
		 Glyf  10  -> PSGlyf Name #   8, 'acmdl-square'

```

Not sure if it is related with an install error message on the name table that macOS shows:
![install-error](https://user-images.githubusercontent.com/11231644/153927499-dc463ed4-d069-4716-9b7a-a33f027e23bb.png)

Can you please look into it?

**Comment by nfrerebeau** [comment]
I can't reproduce the problem on my side :

```
ttfdump academicons.ttf | egrep -i mtmt
		 Glyf 136  -> PSGlyf Name # 134, 'mtmt'
		 Glyf 137  -> PSGlyf Name # 135, 'mtmt-square'
```

**Comment by diogo-fernan** [comment]
It seems to be working now with the file that you shared. Thanks!
