### ISSUE TITLE
Import with `sharelatex`

### ISSUE THREAD

**Issue by gregoire-pointeau** [jpswalsh/academicons#19]
Hello, I tried to import it with `share latex` but for some reason I'm unable to get any icon.
I add a `\RequiredPackage{academicons}` and I have the `academicons.sty` imported and the `academicons.tff` also.
Is there something specific to be able to use it on `share latex` ?
Thank you

**Comment by diogo-fernan** [comment]
@gregoire-pointeau `academicons.tff` needs to be installed on the system. Simply copying the font file to the LaTeX code folder produces no effect.

By the way, the `academicons` LaTeX package is not maintained by the author of this GitHub repository (the author of the font). I suggestion you to post your LaTeX questions on http://tex.stackexchange.com/ from now on.

I am the author and maintainer of the `academicons` package.

**Comment by gregoire-pointeau** [comment]
Ok, thank you for your response, I'll check on `stackexchange` !
