### ISSUE TITLE
Academia.edu, Scopus, figshare, zotero, zenodo

### ISSUE THREAD

**Issue by benmarwick** [jpswalsh/academicons#2]
Here are a few additional suggestions. I love the set you've made already (I'm using them here: http://faculty.washington.edu/bmarwick/), thanks for making them available.

**Comment by dtnedry** [comment]
I've made Academia.edu and Zotero (should be able to push these tomorrow).

Figshare seems to only have this logo:
![spiralsticker](https://cloud.githubusercontent.com/assets/10324632/5603466/678514de-937e-11e4-8d69-86cef1e6e709.png)

This obviously won't scale to small sizes too well. Is there another one that I'm not aware of? I've made one for this logo anyway, and the non-square version won't look too bad above `fa-2x`, albeit without the distinctive colours.

Could you provide an example of an icon for Scopus and Zenodo? Scopus are using a (temporary?) ten year anniversary logo at the moment, while Zenodo has a magnifying glass as the favicon that doesn't seem to be used anywhere else.

**Comment by emmanuel-risler** [comment]
Hi JP

thank you for your very nice work, I will use it for my webpage (currently not online yet). 
Here are two more suggestions (mainly for maths and computer science):
- Zentralblatt MATH https://zbmath.org/
- DBLP (Digital Bibliography & Library Project) http://dblp.uni-trier.de
I do not know if those institutions have a logo in black and white, maybe the simplest would be to ask them ? 

Best regards
Emmanuel

**Comment by khinsen** [comment]
I'd like to add a vote for [Zenodo](http://zenodo.org/). And thanks for all the good work!

**Comment by oliviaguest** [comment]
Thanks from me again! And yes, super useful, I linked to academicons from here too: http://oliviaguest.com/license/ :smile:

**Comment by jpswalsh** [comment]
This issue thread is a bit of a mess!

I've looked into all of the suggestions made here, and if I haven't added them yet it's because I can't find a usable logo. If you really want the icon, then please find a good example of a small logo and then open a new issue with the file attached (high resolution raster, or ideally vector). I'll then add it to the next version.
