### ISSUE TITLE
Update academia.edu icon with new look

### ISSUE THREAD

**Issue by sabgaby** [jpswalsh/academicons#20]
Academia.edu has rebranded itself with a new look.

![academia-icon1](https://cloud.githubusercontent.com/assets/5911330/15012068/ee207456-11f5-11e6-9215-a01780a5420f.png)

[academia icon.svg.zip](https://github.com/jpswalsh/academicons/files/248599/academia.icon.svg.zip)
I am attaching an SVG in ZIP file.

**Comment by jpswalsh** [comment]
Thanks! Updated in v1.7.0.

**Comment by JoeyStanley** [comment]
Thanks for the icon!
