### ISSUE TITLE
ResearcherID (Reuters)

### ISSUE THREAD

**Issue by rgeorgi** [jpswalsh/academicons#21]
This is a tricky one, because I don't believe Reuters has any branding for ResearcherID aside from their [overall corporate logo](http://tguillerme.github.io/images/logo-RID.png), which looks near-identical to figshare.

I've seen another [icon as just "ID" in Reuters' colors](https://www.newcastle.edu.au/__data/assets/image/0006/152592/researcherid-icon.png), but it's unfortunately also very similar to ORCID's "iD" branding.

**Comment by javierecc** [comment]
They do also have the attached small logo.
![badge_sm](https://cloud.githubusercontent.com/assets/25502943/22545363/c494bd48-e938-11e6-8cad-853593043adc.gif)

**Comment by davidjb** [comment]
FYI the ResearcherID badges (eg http://labs.researcherid.com/mashlets/rid/mashletsServer.jsp?rid=F-9674-2010&mid=ResearcherIDBadge) are about as close to 'official' branding as possible.  That's where @javierecc's logo is from.

By eye, it looks like the `R` might be a bolded version of the ResearcherID logo's `R` (eg  http://labs.researcherid.com/mashlets/rid/resources/images/rid_labs_logo.gif) but 16x16 isn't much to go on.

**Comment by DanielBaird** [comment]
The R icon, and the blue colour, appears to be from the old Reuters logo.

http://www.underconsideration.com/brandnew/archives/the_biggest_collection_of_dots.php

So, given they've apparently abandoned the branding of ResearcherID, it seems reasonable to me to make a custom square in Reuters orange with `𝗥` or `ʀ𝗜𝗗` or something.

**Comment by bgajus** [comment]
Just wondering if there had been any decision or plan for how to handle this particular icon.

**Comment by jpswalsh** [comment]
Added to v1.8.6.
