### ISSUE TITLE
icon request: depsy

### ISSUE THREAD

**Issue by drammock** [jpswalsh/academicons#28]
[depsy](http://depsy.org/) mines GitHub to determine dependency relationships and estimate contributor credit.  Their favicon is a circled "d" and is probaby an easier choice than their full logo (which would probably be hard to read at small sizes).

**Comment by andreas-h** [comment]
logos: [PSD](https://github.com/Impactstory/depsy/blob/master/static/img/favicon.psd) [PNG](https://github.com/Impactstory/depsy/blob/master/static/img/favicon.png)

**Comment by jpswalsh** [comment]
Added to v1.8.0.
