### ISSUE TITLE
Order of CSS link in <head>

### ISSUE THREAD

**Issue by pdowland** [jpswalsh/academicons#3]
May not be an issue, but, when I set this up, the fa-2x option did not work (rendered same size with or without it).  However, in tinkering I placed the CSS file line *before* the font-awesome one and it works fine...

E.g. the following worked for me : 

	<link href='academic-icons/academicons.css' rel='stylesheet' type='text/css'>
	<link href='font-awesome/css/font-awesome.min.css' rel='stylesheet' type='text/css'>

putting them the other way round broke the fa-2x option (for me).

This aside, I love these icons (having been watching the +1's on the FontAwesome support list for some time!). Keep up the good work :D :+1:

**Comment by dtnedry** [comment]
Yea, this seems to be the case for me, too. I'll update the instructions to mention this.

I'll leave the issue open in case anyone can think of a way to stop `academicons.css` from interfering with those classes.

**Comment by jpswalsh** [comment]
I've fixed this with a heavy-handed duplication of Font Awesome code to prevent the overwrite. Not pretty, but it works.
