### ISSUE TITLE
ACM icon

### ISSUE THREAD

**Issue by alansaid** [jpswalsh/academicons#30]
An [ACM DL](http://dl.acm.org) icon would be great
A logo is available [here](http://s3.amazonaws.com/libapps/customers/3442/images/ACMDL_Logo_Alt_Color.png) (updated to the correct one)
Favicon [here](http://dl.acm.org/favicon.ico)

**Comment by fkelbert** [comment]
+1

**Comment by jpswalsh** [comment]
Added to v1.8.6. (Think I added a different ACM logo earlier by mistake..)
