### ISSUE TITLE
Repec.org

### ISSUE THREAD

**Issue by ppoppitz** [jpswalsh/academicons#31]
May I suggest adding the following icon. Repec services are very popular within economics:
RePEc.org (http://repec.org/favicon.ico)

**Comment by jpswalsh** [comment]
Anything higher resolution I could work with? If you find it, please add it here.

**Comment by bquast** [comment]
Just noticed this, I added one specifically for IDEAS

https://github.com/jpswalsh/academicons/issues/59

**Comment by jpswalsh** [comment]
I added IDEAD/RePEc to v1.8.6. Can this be closed?

**Comment by ppoppitz** [comment]
I think so too. Thanks
