### ISSUE TITLE
Piazza

### ISSUE THREAD

**Issue by rvuduc** [jpswalsh/academicons#32]
Many university classes use [Piazza](https://piazza.com) as an online discussion forum. It would be great to get an icon. (It's not a terribly exciting one, being just the 'p' in a box, but maybe that makes it a quick addition?)

**Comment by jpswalsh** [comment]
I couldn't see the logo on the page you linked. If you add it here, I can add it to the next version.

**Comment by rvuduc** [comment]
True, it doesn't really appear there. I guess the next best thing are the mobile app icons. See, for instance, this URL: https://play.google.com/store/apps/details?id=com.piazza.android&hl=en

Or this screenshot: 
![img_1503](https://cloud.githubusercontent.com/assets/5316640/25929150/5cf698d6-35ce-11e7-8954-29a5019e18e7.PNG)

**Comment by jpswalsh** [comment]
Added to v1.8.0.
