### ISSUE TITLE
Would be cool to have a bioRxiv icon...

### ISSUE THREAD

**Issue by dudmanj** [jpswalsh/academicons#34]

**Comment by jpswalsh** [comment]
Does a logo exist? If so, please link it here.

**Comment by sschmeier** [comment]
https://en.wikipedia.org/wiki/BioRxiv#/media/File:BioRxiv_logo.png

favicon looks like this: http://d2538ggaoe6cji.cloudfront.net/sites/default/files/images/favicon.ico

**Comment by jpswalsh** [comment]
Added to v1.8.0.
