### ISSUE TITLE
Icon for Curriculo Lattes

### ISSUE THREAD

**Issue by quigonjeff** [jpswalsh/academicons#36]
First and foremost, thanks a lot for the incredible font. Very useful.

I would like to ask for the addition of the [Curriculo Lattes](http://lattes.cnpq.br/)' logo. Curriculo Lattes is a platform maintained by the Brazilian government, and if a researcher wants to ever have his research funded by a government agency they have to be registered in this platform. So, for us from Brazil, it is quite important.

![lattes-172x172](https://cloud.githubusercontent.com/assets/829487/19294883/ecba2708-9006-11e6-86c7-b467305cc88b.png)

If I can help somehow, please let me know. I don't know anything about how to make a font, but I am a quick learner. :-)

**Comment by vcaldas** [comment]
I have the SVG file, but not sure how to font files work.

**Comment by jpswalsh** [comment]
@vcaldas If you can upload it here or email it to me, that would be very helpful.

**Comment by vcaldas** [comment]
@jpswalsh  Sent via webmail, hope it works!

**Comment by filipesaraiva** [comment]
+1 :)

**Comment by filipesaraiva** [comment]
In Font Awesome there is an issue with this same request with a [comment](https://github.com/FortAwesome/Font-Awesome/issues/6883#issuecomment-307194891) where you can find files to add this icon. May it can help you to provide Lattes icon in academicons.

**Comment by jpswalsh** [comment]
Added to v1.8.6.
