### ISSUE TITLE
icon request: SSRN

### ISSUE THREAD

**Issue by ChandlerLutz** [jpswalsh/academicons#42]
Icon request for SSRN https://ssrn.com/en/

**Comment by RyanMcCarl** [comment]
I second this. Thanks for the great project.

**Comment by jonathan-g** [comment]
Exemplars:

I can't find a vector icon, but here are two high-resolution raster images.

![2872385_ssrn-color_square_highres](https://user-images.githubusercontent.com/5304060/27064729-74d80d86-4fbe-11e7-9e73-53e7e408750d.jpg)

and

![1200x630bb](https://user-images.githubusercontent.com/5304060/27064732-77176da8-4fbe-11e7-8c9b-02da0c6be16c.jpg)

**Comment by davidjb** [comment]
The URL's source for SSRN has an SVG at https://static.ssrn.com/cfincludes/img/favicon/safari-pinned-tab.svg?v=2 but the URL is a 404.  That page says to report problems to admin@ssrn.com, which I did.  Let's see if there's any response.

**Comment by davidjb** [comment]
Curiously, SSRN uses at least 3 notably-different logos.  The tiny main logo at https://ssrn.com/, which is also in the favicon, looks like this:
![index](https://user-images.githubusercontent.com/1002811/28204045-a4ccd246-68bf-11e7-87ab-cbd44fb36e23.png)
Its letters are far closer together, the `S` serifs are different, plus the bottom-left serif of the `N` is missing.

I asked SSRN for their vectorised logo for another purpose, but with deadlines looming, I made the their logo into an SVG, here: [ssrn.svg.zip](https://github.com/jpswalsh/academicons/files/1147734/ssrn.svg.zip)  You're welcome to use it without restriction.

The font is Goudy Old Style Regular for both the main SSRN letters and byline, in case anyone wants to have a go.

**Comment by rliivoja** [comment]
+1 :)

**Comment by sahmurx** [comment]
Hi , I have an idea of SSRN logo. How should the size of the logo be?

**Comment by kurtmunz** [comment]
+1

**Comment by jonathan-g** [comment]
> The URL's source for SSRN has an SVG at https://static.ssrn.com/cfincludes/img/favicon/safari-pinned-tab.svg?v=2 but the URL is a 404. That page says to report problems to [admin@ssrn.com](mailto:admin@ssrn.com), which I did. Let's see if there's any response.

I just checked and the link for the SVG icon works now.

**Comment by Mannala** [comment]
how can i add this icon to the academics theme of hugo in order to use it?

**Comment by Wenzhi-Ding** [comment]
Hey guys, I would like to provide an SSRN icon I made, in the same format as [Font Awesome - Square Brand Icon](https://fontawesome.com/icons/facebook-square?style=brands).

It works like this:
![image](https://user-images.githubusercontent.com/30380959/86781806-ebac9080-c090-11ea-9c40-028a9795de02.png)

And here is a link:
https://github.com/Wenzhi-Ding/Wenzhi-Ding.github.io/blob/master/assets/img/ssrn_fontello.svg

The AI file (feel free to modify it to your own style):
https://github.com/Wenzhi-Ding/Wenzhi-Ding.github.io/blob/master/assets/img/SSRN.ai

You can upload the SVG to [Fontello](http://fontello.com/) to make your own icon package, in case you can't wait for the authors to update this repo.
