### ISSUE TITLE
Icon request: NASA ADS

### ISSUE THREAD

**Issue by ntessore** [jpswalsh/academicons#45]
The SAO/NASA Astrophysics Data System is the standard database for astronomy and astrophysics publications, and most astronomers are linking to their publication record there. It would be great to have an academicon for this.

The new ADS site is https://ui.adsabs.harvard.edu, and it features the an [icon in SVG format](https://ui.adsabs.harvard.edu/styles/img/transparent_logo.svg).

**Comment by jpswalsh** [comment]
Added to v1.8.0.
