### ISSUE TITLE
arXiv icon

### ISSUE THREAD

**Issue by edugp** [jpswalsh/academicons#5]
First, thanks for this great piece of work, I am starting to use the Google Scholar and Research Gate icons on my website. However, I miss an **arXiv icon** in this wonderful academic collection. I opened an [issue in FontAwesome] (https://github.com/FortAwesome/Font-Awesome/issues/3633) some time ago, but was ignored as with most of the academic requests...

Here are two images based on the favicon:
http://arxiv.org/favicon.ico (lower quality)
http://www.userlogos.org/node/2070 (better quality, nor the water effect or the text are part of the logo)

**Comment by jpswalsh** [comment]
Thanks for the feedback!

I've added this now (v1.4). There didn't seem to be any official logo beyond that old 48x48 favicon. I contacted Paul Ginsparg and he told me that the favicon was all that he'd ever made, so I remade it using that icon as a guide. (Paul has seen the remake and was happy for it to be used.)

**Comment by edugp** [comment]
Awesome, thanks! I am using it right now :+1:
