### ISSUE TITLE
Use of icon as part of other element changes the font face

### ISSUE THREAD

**Issue by fkelbert** [jpswalsh/academicons#50]
I am using the icons as follows:
`<a class="ai ai-google-scholar-square ai-3x" href="http://www.example.com">example.com</a>`

Unfortunately, this changes the font type of the "example.com" Link due to the definition of class type `.ai`.

I get the desired result (Link in default font and prepended icon), when chaning the CSS as follows:

Old:
```
.ai {
	display:inline-block;
	font:normal normal normal 14px/1 Academicons;
	font-size:inherit;
	text-rendering:auto;
	-webkit-font-smoothing:antialiased;
	-moz-osx-font-smoothing:grayscale;
}
```

New:
```
.ai {
	display:inline-block;
	font:normal normal normal 14px/1 Academicons;
	font-size:inherit;
	text-rendering:auto;
	-webkit-font-smoothing:antialiased;
	-moz-osx-font-smoothing:grayscale;
}
```

Is there any reason for not defining the CSS like this?

**Comment by jpswalsh** [comment]
Firstly, I can't spot the difference between the two blocks of code. Perhaps it's just too early in the day for me, but could you please point to where the difference is?

Secondly, the way you are using the icons seems strange to me. I would do it like so:

`<a href="http://www.example.com"><i class="ai ai-google-scholar-square ai-3x"></i>&nbsp;example.com</a>`

The non-breaking space is optional, but I often find that the icon is too close to the text without it. Using a normal space can sometimes cause the icon and the text to separate, which is often undesirable.
