### ISSUE TITLE
update of the dblp icon?

### ISSUE THREAD

**Issue by mra42** [jpswalsh/academicons#51]
First of all, thanks for doing this project. This is really a nice and useful set of icons, please keep up the good work!

However, the dblp icon seems a little bit off the mark to me, up to the point I find it personally quite hard to recognize its shape. I derived a monochrome version from the original dblp signet file and attached it as SVG to this issue ticket. You may use this file to update the dblp icon if you like.

[icon_dblp_bw.svg.zip](https://github.com/jpswalsh/academicons/files/1108556/icon_dblp_bw.svg.zip)

In case you need any further sources for the dblp icon please just let me know.

~MRA

(edit: upload failed the first time)

**Comment by jpswalsh** [comment]
Yes, it's difficult to work with a logo that relies so heavily on colour, and I agree that the current logo isn't a great interpretation. Looking at the file you sent, I see that your solution was to drag the right part of the logo away from the left to create a separation:

![mra42-dblp](https://user-images.githubusercontent.com/10324632/34922552-28d0372c-f957-11e7-9ccb-a39e9c0a1cc4.jpg)

While this does simplify the logo somewhat, it also alters the fundamental metrics of the logo. Let's think about designs that make the logo more recognisable without messing with the proportions!

**Comment by mra42** [comment]
Ok, I understand. I went back to the original SVG of the signet and tried to "cut out" the separation from inside the lower part while leaving the outer proportions as they are. I hope this is more fitting.

[icon_dblp_bw.svg.zip](https://github.com/jpswalsh/academicons/files/1914757/icon_dblp_bw.svg.zip)

Please let me know if you need anything else.

~MRA

**Comment by ericcornelissen** [comment]
Hey @mra42, we're looking for an SVG of the dblp logo for [Simple Icons](http://simpleicons.org/) (as request in [this issue](https://github.com/simple-icons/simple-icons/issues/1080)). Do you mind if we use yours? Could you also provide further sources in that case? (we like to link to an official source when including icons)

**Comment by mra42** [comment]
No problem, go ahead. I'll answer in more detail in the other thread.

**Comment by mra42** [comment]
Brief bump of this issue since it has been over a year since I submitted the updated SVG (see comment from Apr 16, 2018).

If there is anything else I can do to help updating the icon please just let me know.

~MRA
