### ISSUE TITLE
CDN file is wrong

### ISSUE THREAD

**Issue by slurdge** [jpswalsh/academicons#53]
Hello,

It seems that cdnjs has been confused by the unique commit on the tree. The version served is 1.6.0 whereas it believes the version is 1.8.0.
See this file: https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.0/css/academicons.css vs https://raw.githubusercontent.com/jpswalsh/academicons/master/css/academicons.css

I don't know how to force a refresh of CDNjs. Maybe just a commit and push of comment part should be enough. Right now I can't use the CDNjs version because it lacks some icons I need.

If you need any help in resolving this matter, don't hesitate.

**Comment by jpswalsh** [comment]
Not sure how to fix this. Anybody have any suggestions?

**Comment by slurdge** [comment]
I would say there are two  options:
1/ Create a new tag 1.9.0 that would point to the current tip, it should trigger an update from cdnjs.
2/ Make a commit into the README and point 1.8.0 to it.

The strange thing is that the current repository has only two commits? Did you squash all the previous commits into 1.8.0 ?

**Comment by jpswalsh** [comment]
I just made a new release (v1.8.1) that points to the current tip. We'll see if that does anything.

Yea, I squashed them all. I forget exactly why, but it fixed some issue I was having with pushing from GitHub desktop. Probably could have done it in a more elegant way if I knew what I was doing.

**Comment by slurdge** [comment]
It works :-)
https://cdnjs.cloudflare.com/ajax/libs/academicons/1.8.1/css/academicons.css

Thank you!
