### ISSUE TITLE
Icon request: R

### ISSUE THREAD

**Issue by stephlocke** [jpswalsh/academicons#57]
Would it be possible to add the R-project as an icon? 

There's an svg already so it might be minimal work https://r-project.org/logo

**Comment by robroot** [comment]
I support this request for an R-project icon, and humbly request that the logo for RStudio also be considered. It is available, together with careful description of use intended to avoid the need for legal negotiation, at https://www.rstudio.com/about/logos/ and the logo in black and white is available at https://www.rstudio.com/wp-content/uploads/2014/07/RStudio-Logo-All-Gray.png (which is only a png. Sorry. Disclaimer: I am only a user of RStudio, not a developer, and I have no business relationship with the RStudio project!

**Comment by stephlocke** [comment]
fwiw, we recently got R into font awesome 💪 https://fontawesome.com/icons/r?style=brands

**Comment by chmue** [comment]
> fwiw, we recently got R into font awesome muscle https://fontawesome.com/icons/r?style=brands

Thanks for pointing this out! 

Fyi, the current link seems to be https://fontawesome.com/icons/r-project?style=brands
