### ISSUE TITLE
Icon request: INSPIRE 

### ISSUE THREAD

**Issue by andrewfowlie** [jpswalsh/academicons#58]
I can't find an icon for http://inspirehep.net/ - it's the main website for academics and their publication/citation history in high-energy physics, see e.g. Ed Witten's profile http://inspirehep.net/author/profile/E.Witten.1

I'm not sure what the icon should be; maybe something like the RHS of the logo

http://inspirehep.net/img/inspire_logo_hep.png

**Comment by jpswalsh** [comment]
Is `ai-inspire` no good for you? I forget now where that came from, but it looks to be the same organisation.

**Comment by andrewfowlie** [comment]
Nice one! That's perfect. Very sorry don't know why I didn't see that.
