### ISSUE TITLE
Icon request RePEc IDEAS

### ISSUE THREAD

**Issue by bquast** [jpswalsh/academicons#59]
IDEAS is the standard resource for economists.

https://ideas.repec.org/

There is a roughtly 1x1 logo that can be reduced to monochrome:

https://ideas.repec.org/ideas2.gif

**Comment by ppoppitz** [comment]
IDEAS has a new logo:
https://blog.repec.org/2018/02/15/ideas-inaugurates-new-design/

with a better source for monochrome:
https://ideas.repec.org/ideas4.jpg

**Comment by ppoppitz** [comment]
no vector file, but better jpg:
https://ideas.repec.org/images/IDEAS-lightbulb-mark.jpg
