### ISSUE TITLE
Please create an icon for Scopus

### ISSUE THREAD

**Issue by alezunino** [jpswalsh/academicons#68]
Scopus is a very popular service for searching scientific papers which includes many productivity metrics. This is the link: https://www.scopus.com/

**Comment by thomasfedb** [comment]
The best roughly 1x1 logo for Scopus is their favicon here: https://www.scopus.com/static/proteus-images/favicon.ico?ver=1.0

Having poked around their webpage, I'm fairly confident that their logo is simply "Scopus" written in Nexus Sans using the 400 weight. I'd extrapolate then that their favicon is simply "SC" in the same font.

**Comment by xfim** [comment]
Is there a chance to help to have the Scopus icon?

**Comment by belalik** [comment]
Hello - also willing to help towards the inclusion of Scopus icon..

**Comment by marianamalta** [comment]
Hi, We also really need it in our organisaton since it is a very important service. We already use other academic icons.

**Comment by sguazt** [comment]
Hi, I'd like to requiest the Scopus icon me too. Thank you for your time.

**Comment by junruidi** [comment]
I totally agree and would love that too. Thank you

**Comment by marcospln** [comment]
So do I! Maybe we can help you ;)

**Comment by thomasfedb** [comment]
This is still something I'd be very keen for. Very happy to assist with adding the icon @jpswalsh if you added details of the process to the README?

**Comment by thomasfedb** [comment]
Here's a larger version of the square favicon:
![](https://www.fer.unizg.hr/_pub/themes_static/fer2016/default/img/scopus-icon.png)

This might also be an option:
![](https://ijog.geologi.esdm.go.id/public/site/images/nana/Icon_-_Scopus.png)

**Comment by jAniceto** [comment]
This is really the only major institution missing in the pack. I second the request. Any of the above would be fine.

**Comment by gianfrancodp** [comment]
> Here's a larger version of the square favicon:
> ![](https://camo.githubusercontent.com/ec1c790ef8fcb75b37bccd96b0f51869dc2be534/68747470733a2f2f7777772e6665722e756e697a672e68722f5f7075622f7468656d65735f7374617469632f666572323031362f64656661756c742f696d672f73636f7075732d69636f6e2e706e67)
> 
> This might also be an option:
> ![](https://camo.githubusercontent.com/aff4faddb6c453dac156f873a80e9e0b21d92f86/68747470733a2f2f696a6f672e67656f6c6f67692e6573646d2e676f2e69642f7075626c69632f736974652f696d616765732f6e616e612f49636f6e5f2d5f53636f7075732e706e67)

**Comment by DanySK** [comment]
I second the request as well

**Comment by davidjb** [comment]
For anyone who wants an SVG icon or logo:

* SC favicon: [scopus.svg.zip](https://github.com/jpswalsh/academicons/files/4620278/scopus.svg.zip)
* SC icon, no background: https://github.com/simple-icons/simple-icons/pull/3068 (add support over there :+1: )
* Scopus® logo (white): [ScopusR_Wmk_White_RGB.svg.zip](https://github.com/jpswalsh/academicons/files/4620286/ScopusR_Wmk_White_RGB.svg.zip)
* Scopus® logo: [ScopusR_Wmk_RGB.svg.zip](https://github.com/jpswalsh/academicons/files/4620285/ScopusR_Wmk_RGB.svg.zip)

The first two are my own creation and are public domain (CC0 license); the third is from  https://www.elsevier.com/__data/assets/file/0008/624869/ScopusR_Wmk_White_RGB.svg and the last is me applying the Scopus orange color.
