### ISSUE TITLE
Icon request: Open Science Badges

### ISSUE THREAD

**Issue by adilsaribay** [jpswalsh/academicons#77]
It would be amazingly useful especially for CVs if open science badges (open data, open materials, pre-registered, etc.) were added.  

Open Science Foundations provides files that I think meet your criteria:
https://osf.io/tvyxz/files/

Thanks in advance.

**Comment by buraczku** [comment]
+1 here. Open science badges would be a valuable addition to the package

**Comment by eplebel** [comment]
+1 also!

**Comment by naaffaan** [comment]
+1 here,
