### ISSUE TITLE
Icon request: Closed Access

### ISSUE THREAD

**Issue by HanjoHamann** [jpswalsh/academicons#79]
Thank you, James! I truly love the Academicons, and find the Open Access icon particularly useful. I could use it even better in many circumstances if I could contrast it with a Closed Access icon, such as this:

https://de.wikipedia.org/wiki/Datei:Closed_Access_logo_transparent.svg

Any chance you might include this in the icon set?

**Comment by rschmehl** [comment]
I would also find this very useful
