### ISSUE TITLE
Icon Tutorial?

### ISSUE THREAD

**Issue by ChemPaul** [jpswalsh/academicons#8]
I was wondering if you could post some basic directions on how you make the fonts and make them compatible with Font Awesome commands. I already have the vector graphic that I'd like to use, and I have had minor success in making a font using fontastic.me, but it's not compatible with the other commands (like fa-3x). I'm already using some Font Awesome icons and a few of your Academic Icons, I just want to add something else to my own personal font. Thanks for your help!

**Comment by jpswalsh** [comment]
I'm not sure why the fonts you've generated aren't compatible with the Font Awesome classes, since those are quite general. I'd recommend using [IcoMoon](http://icomoon.io). You can actually import the Academicons SVG file into a new project on there and inspect all the icons in quite some detail.

**Comment by ChemPaul** [comment]
Thanks. I'll try that out and see if I can get it to work.
