### ISSUE TITLE
Request for Elsevier Icon

### ISSUE THREAD

**Issue by anubane** [jpswalsh/academicons#80]
Please create an Icon for **Elsevier**, given it is widely used and immensely popular publication platform.
I have attached a .svg file for convenience.
[Elsevier.zip](https://github.com/jpswalsh/academicons/files/2122567/Elsevier.zip)

or direct link: https://www.elsevier.com/__data/assets/file/0003/278661/ELS_NS_Logo_2C_RGB.svg

**Comment by leouieda** [comment]
This probably violates their trademark. Is there a page where they specify how their logo can be used? If there isn't, then it usually means that you can't reuse their logo.

**Comment by anubane** [comment]
@leouieda @jpswalsh : I have communicated the concerns to Elsevier and they have granted permission to reproduce the "Non Solus" Logo as an icon.

Please check the email from Elsevier: 
[Elsevier_Permission.pdf](https://github.com/jpswalsh/academicons/files/2154938/Elsevier_Permission.pdf)

(In case you do create a logo, please take care of the riders.)

**Comment by leouieda** [comment]
@anubane notice that the letter says that they grant **you** permission to use it on **your** website. That is very different from including it in an open-source icon set that can be used by **anyone** on **any** website.
