### ISSUE TITLE
PsyArXiv 

### ISSUE THREAD

**Issue by oliviaguest** [jpswalsh/academicons#82]
Any chance you can include PsyArXiv icon, please?

Poor quality (sorry!) reference: https://psyarxiv.com//assets/osf-assets/files/preprints-assets/psyarxiv/square_color_transparent-09b2baefd6aac7dde2d250b56e2929482c6bed55.png

**Comment by davebraze** [comment]
+1 to this. 

Here are some svg files that may be a better starting point for an icon:
https://github.com/davebraze/david-braze/tree/master/static/img

**Comment by emilynakka** [comment]
Another +1!

I have reached out to the PsyArXiv team to request the icon files, and although they did not have a vector file, they provided the attached PNG, which has a fairly high resolution. Many thanks for your consideration of this icon request and for all of your work to date on Academicons.

![Logo PsyArXiv red-test-deep](https://user-images.githubusercontent.com/36014646/81956452-f129b500-95d0-11ea-9b31-d374da4b6dfe.png)
