### ISSUE TITLE
Possible addition: PhilPapers

### ISSUE THREAD

**Issue by twsh** [jpswalsh/academicons#9]
Lots of philosophers use [PhilPapers](http://philpapers.org), and have profiles on there where they list their publications. I don't know if they have an icon available for you to use. If they do it would be a nice addition.

**Comment by jpswalsh** [comment]
They don't seem to have a logo. If you find one, paste it here and I'll add it to the next version.

**Comment by inthecave** [comment]
I too would like a PhilPapers icon, but am disappointed they do not have a logo.

PhilPapers is designed and maintained by the Centre for Digital Philosophy, though, and they have a logo. Perhaps that would work? Here is an image

![cdp-logo](https://cloud.githubusercontent.com/assets/9028673/16593585/fe95e7aa-42b3-11e6-857e-4f7afc67843d.gif)

**Comment by twsh** [comment]
PhilPapers recently ran a competition for a new logo: http://philpapers.org/design_contest.html I haven't seen anything about the results. Maybe it's better to wait until they do their rebranding?

**Comment by inthecave** [comment]
Ah yes, in that case, I think so. Especially since a condition of the contest is providing a scalable vector image

**Comment by dbourget** [comment]
The PhilPapers Foundation is happy to provide an SVG file for the new PhilPapers logo. I'll email it separately.

**Comment by jpswalsh** [comment]
Added to v1.8.0.
