### ISSUE TITLE
Icon Request: HAL

### ISSUE THREAD

**Issue by Bertbk** [jpswalsh/academicons#99]
Hello and thanks for this great project!

In France, researcher are now asked to publish their results on [HAL](https://hal.archives-ouvertes.fr/) which is basically an open archive for scientific publication. Having an icon for HAL would then be of great interest for us!

Problem is, the usual logo is not 1:1 scaled:
![LogoHAL](https://user-images.githubusercontent.com/5602767/56238596-217de780-608f-11e9-88ca-d9fef90f7458.PNG)

The favicon and this adapted logo (still usual) use some workaround by adding a circle :
![hal](https://user-images.githubusercontent.com/5602767/56238622-2f336d00-608f-11e9-8643-c66683ffcf16.png)

This might be an idea for us. I use my poorly Gimp talent and this would give something like this:

![hal_gimp2](https://user-images.githubusercontent.com/5602767/56239127-7a01b480-6090-11e9-9210-107eb515f1ee.png)

or without the "white bar"
![hal_gimp3](https://user-images.githubusercontent.com/5602767/56239196-9c93cd80-6090-11e9-89c8-9a94e846e1c4.png)

  
I hope these two could be a good candidate. If you believe they could be added to the database, I'll be more than happy to help!

**Comment by pjox** [comment]
This is one of the most important platforms for publishing pre-prints in France. Moreover, there are currently some efforts to have an European HAL (based on the current HAL which is by far the most advanced OA repo in EU) in the context of the OESC (with a tender for an EU Open Research Publishing Platform https://etendering.ted.europa.eu/cft/cft-display.html?cftId=5034)

This icon is really needed.

**Comment by Bertbk** [comment]
@pjox For your information, my suggested "HAL" icon has [just been accepted in ForkAwesome](https://github.com/ForkAwesome/Fork-Awesome/pull/204) couple of minuts before. So I guess it will be released in next ForkAwesome release.

It is not academicons unfortunately, but maybe it will also arrive here! :)

**Comment by pjox** [comment]
Amazing news! 🎉 I hope they add it here as well!

**Comment by Bertbk** [comment]
You can also add a ":+1:" reaction at the issue I raised at [Font Awesome](https://github.com/FortAwesome/Font-Awesome/issues/15594) ;-)
